### ISSUE TITLE
problem with user imput

### ISSUE THREAD

**Issue by klaus108** [PitNox/birthdays#2]
avoid changing input into string manually
so we add str() to the sys.arg command in the main.py

**Comment by xuelanli** [comment]
https://github.com/PitNox/birthdays/commit/b55bd197a1b3a57cd6624eefa5578193dce8a2f6

issue not successfully solved yet.

**Comment by teorad** [comment]
Solved user name input with commit: https://github.com/PitNox/birthdays/commit/6818de2ca74c787878db2aa708a88d2e5266dcdc
