### ISSUE TITLE
Clean code main_task3.py

### ISSUE THREAD

**Issue by PitNox** [PitNox/birthdays#5]
- Clean code and comment it;
- accept from user strings without "";
- Complete argparse options

**Comment by xuelanli** [comment]
No need for inverted commas in user input main_task3.py   https://github.com/PitNox/birthdays/commit/e5ed8f72267da7758d7812f02336fd805efe1a11

**Comment by xuelanli** [comment]
clean version of argparse task https://github.com/PitNox/birthdays/commit/a31646788ff387f25ed4ce53b483733c59009a1a

**Comment by barbaradanzo** [comment]
Solved issue e5ed8f72267da7758d7812f02336fd805efe1a11 . 9a82748af3b0956990136f132d9acd8745f566a8 , f03d9ff66c27b63b6853c5e4b412e209e9e96925
