### ISSUE TITLE
Create and implement file .csv

### ISSUE THREAD

**Issue by PitNox** [PitNox/birthdays#6]

**Comment by teorad** [comment]
Added a csv file with the data, with the commit: https://github.com/PitNox/birthdays/commit/cdceccdd8dcbcb76a41156e2b22a197dd3e5849f

**Comment by barbaradanzo** [comment]
Solved issue 15df91ebb18f2e0b8cbf6e0d417ce59db54cd952 , 006419bd776dcf88cc0b6e4b995ffa359a5a953e , cdceccdd8dcbcb76a41156e2b22a197dd3e5849f
